### PR TITLE
Make Coordination self contained wrt HTTP handling (closes #93)

### LINKED ISSUE #93: Outgoing Connection 'caches' the IP in Coordination
In `Constructr.scala` the `Connection` is initialized and the solved IPs are cached but it's using the same one in every flow materialization. As a result, if that Consul node got down, ConstructR won't try with another IP. 

```scala
val connection = Http()(context.system).outgoingConnection(host, port)
Coordination("akka", context.system.name, context.system.settings.config)
            (connection, ActorMaterializer())
```

This behaviour might be observed during DNS resolution of coordination cluster nodes.

Possible related info:

https://github.com/akka/akka/issues/19419
https://gitter.im/akka/akka?at=569552acee13050b38a32091

### PR DESCRIPTION
**Pull request by hseeberger**

### CODE REVIEW

**Comment by hseeberger** [comment]
@juanjovazquez, could you and your team please take a look if the changes wrt `Coordination` implementations (mainly the constructor taking an `ActorSystem` instead of a connection, etc.) work for you Consul implementation?

**Comment by juanjovazquez** [comment]
Of course, we'll have a look into it ASAP!.

**Comment by juanjovazquez** [comment]
@hseeberger Tested and working like a charm. Thanks!.

**Comment by hseeberger** [comment]
@juanjovazquez, I wonder whether coordination should be an actor. Do you have any concerns?

**Comment by juanjovazquez** [comment]
@hseeberger No problem a priori. Like in Hollywood, this business is about actors after all, right?. ;)

**Comment by hseeberger** [comment]
Indeed: "Everything is an actor!" (Carl Hewitt)
I might update this PR, i.e. switch over to an actor, and ask for you feedback again.

**Comment by juanjovazquez** [comment]
It works for me.

**Pull request merged**
