### PR TITLE
Pass LoggingAdapter to Coordination (closes #96)

### LINKED ISSUE #96: The party creating the Coordination instance should pass in a LoggingAdapter
It would be nice to have access to the Akka `logger` in every particular coordination implementation.

See https://github.com/Tecsisa/constructr-consul/issues/9

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by hseeberger** [comment]
@raboof, thanks for the PR, but this is not aligned with the conclusion we arrived at in #96: we want to use `FlowOps.log` instead of extending the API of `Coordination`.

**Comment by raboof** [comment]
Sorry, I misunderstood our conclusion then: we arrived at "the party creating the Coordination instance should pass in a specific LoggingAdapter" - this PR was intended as an implementation of that conslusion :).

(I still agree we want to use `FlowOps.log` in the `Coordination`, but this seemed like a prerequisite for achieving that logging to a more sensible logger than `akka.stream.Materializer`)

**Comment by hseeberger** [comment]
When creating an `ActorMaterializer` one can specify a custom logger.

But I'm currently working on #93 which might get along without materializer. Let's revisit logging then, maybe your PR will become relevant again ;-)

**Comment by raboof** [comment]
Hmm that doesn't seem easy: the only `ActorMaterializer` akka 2.4.3 provides is

```
private[akka] case class ActorMaterializerImpl(system: ActorSystem,
                                               override val settings: ActorMaterializerSettings,
                                               dispatchers: Dispatchers,
                                               supervisor: ActorRef,
                                               haveShutDown: AtomicBoolean,
                                               flowNames: SeqActorName) extends ActorMaterializer { 
  import akka.stream.impl.Stages._
  private val _logger = Logging.getLogger(system, this)
  override def logger = _logger
```

I'll hold off until your refactor in #93 is done then :)

**Comment by hseeberger** [comment]
You are right, I was confused ;-)
Anyway, #93 might change the picture.

**Pull request closed without merging**
